import os
from dotenv import load_dotenv
from google.adk.agents import Agent

# Import decoupled modular tools
from .tools import (
    ingest_firestore_emails,
    parse_clean_journalistic_text,
    produce_and_distribute_podcast
)

load_dotenv()

# -------------------------------------------------------------------------
# Define the Root ADK Agent
# -------------------------------------------------------------------------

PROJECT_ID = os.getenv("GOOGLE_CLOUD_PROJECT")
MODEL_NAME = os.getenv("MODEL_NAME", "gemini-2.5-pro")

if PROJECT_ID != "YOUR_GCP_PROJECT_ID" and not MODEL_NAME.startswith("projects/"):
    model_path = f"projects/{PROJECT_ID}/locations/us-central1/publishers/google/models/{MODEL_NAME}"
else:
    model_path = MODEL_NAME

root_agent = Agent(
    name="wsj_podcast_architect_agent",
    model=model_path,
    description=(
        "Editorial Assistant Agent designed to ingest Wall Street Journal front-page stories, "
        "strip boilerplate formatting and metadata, and synthesize executive audio briefings."
    ),
    instruction="""You are an editorial assistant. 
Here are 5 emails containing Wall Street Journal articles. Strip out all email formatting, disclaimers, and metadata. Extract only the core journalistic text.

When a user requests to extract text from recent WSJ emails or generate a podcast briefing:
1. First invoke `ingest_firestore_emails` to acquire the 5 most recent front-page feature stories from the central database.
2. Next invoke `parse_clean_journalistic_text` to clean and filter the text.
3. Finally invoke `produce_and_distribute_podcast` to generate audio via the Google Podcast API, stage it to Google Cloud Storage, and send the notification email with a secure signed URL.
4. Formulate a complete, polished executive delivery receipt summarizing the exact headlines analyzed and presenting the final Signed URL cleanly.

MANDATORY DISCLAIMER:
You must append these exact disclaimers at the very bottom of every response:
- 'This insight was generated by an AI agent deployed on the Gemini Enterprise Agent Platform.'
- 'Outputs should be validated by Subject Matter Experts (SMEs) before strategic execution.'""",
    tools=[ingest_firestore_emails, parse_clean_journalistic_text, produce_and_distribute_podcast]
)

if __name__ == "__main__":
    print(f"Agent '{root_agent.name}' loaded successfully with model {root_agent.model}.")
